import { useEffect, useMemo, useState } from "react";
import { getAuditLog, getPermissionCatalog, getSecurityUsers, getUserPermissions, saveUserPermissions } from "../../api/SecurityApi";
type Person = { ID_User: number; Name: string; email?: string; role?: string; State: boolean };
const labels: Record<string, string> = { sales: "Ventas", purchases: "Compras", invoices: "Facturación", catalog: "Catálogo", customers: "Clientes", orders: "Pedidos", settings: "Configuración", security: "Seguridad", audit: "Auditoría" };
export default function SecurityPage() {
  const [users, setUsers] = useState<Person[]>([]); const [catalog, setCatalog] = useState<string[]>([]); const [selected, setSelected] = useState<number | null>(null); const [effective, setEffective] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [audit, setAudit] = useState<any[]>([]);
  useEffect(() => { Promise.all([getSecurityUsers(), getPermissionCatalog(), getAuditLog()]).then(([u, p, a]) => { setUsers(u.data); setCatalog(p.permissions); setAudit(a.data); }).catch((e) => setMessage(e.message)); }, []);
  useEffect(() => { if (selected) getUserPermissions(selected).then((data) => setEffective(data.effective)); }, [selected]);
  const groups = useMemo(() => catalog.reduce<Record<string, string[]>>((out, code) => { const group = code.split(".")[0]; (out[group] ||= []).push(code); return out; }, {}), [catalog]);
  const save = async () => { if (!selected) return; setSaving(true); try { const data = await saveUserPermissions(selected, catalog.map((permission) => ({ permission, granted: effective.includes(permission) }))); setEffective(data.effective); setMessage("Permisos guardados correctamente"); } catch (e) { setMessage(e instanceof Error ? e.message : "No fue posible guardar"); } finally { setSaving(false); } };
  return <div className="space-y-6"><section className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-primary">Administración</p><h1 className="text-2xl font-extrabold">Permisos por usuario</h1><p className="text-on-surface-variant">Los cambios individuales prevalecen sobre el rol general.</p>{message && <p className="mt-3 rounded-xl bg-surface-container-low p-3 text-sm">{message}</p>}<label className="mt-5 block text-sm font-bold">Usuario</label><select className="mt-2 w-full rounded-xl border border-outline/30 bg-white px-4 py-3" value={selected || ""} onChange={(e) => setSelected(Number(e.target.value) || null)}><option value="">Selecciona un usuario</option>{users.map((user) => <option key={user.ID_User} value={user.ID_User}>{user.Name} · {user.role} · {user.email}</option>)}</select>{selected && <><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Object.entries(groups).map(([group, permissions]) => <fieldset key={group} className="rounded-2xl border border-outline/20 p-4"><legend className="px-2 font-bold">{labels[group] || group}</legend>{permissions.map((permission) => <label key={permission} className="flex items-center gap-3 py-2 text-sm"><input type="checkbox" className="h-5 w-5 accent-primary" checked={effective.includes(permission)} onChange={(e) => setEffective((current) => e.target.checked ? [...current, permission] : current.filter((item) => item !== permission))}/><span>{permission.split(".")[1]}</span></label>)}</fieldset>)}</div><button disabled={saving} onClick={save} className="mt-5 rounded-xl bg-primary px-6 py-3 font-bold text-white active:scale-[.98] disabled:opacity-50">{saving ? "Guardando…" : "Guardar permisos"}</button></>}</section><section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-extrabold">Actividad reciente</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Fecha</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>Resultado</th></tr></thead><tbody>{audit.map((row) => <tr key={row.ID_AuditLog} className="border-b border-outline/10"><td className="p-3">{new Date(row.createdAt).toLocaleString("es-MX")}</td><td>{row.ID_User || "Sistema"}</td><td>{row.Action}</td><td>{row.Entity}{row.EntityId ? ` #${row.EntityId}` : ""}</td><td>{row.StatusCode}</td></tr>)}</tbody></table></div></section></div>;
}
