import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { jwtDecode } from "jwt-decode";
import { Eye, EyeOff, LoaderCircle, LockKeyhole, Mail } from "lucide-react";
import { toast } from "react-toastify";
import { forgotPassword, loginUser, resetPassword, verifyAuthCode } from "../../../api/authApi/authApi";
import OtpPanel from "../OtpPanel";
import type { Challenge } from "../OtpPanel";

interface LoginProps { onRegister?: (register: boolean) => void }
interface DecodedToken { Rol: string }

export default function Login({ onRegister }: LoginProps) {
  const [form, setForm] = useState({ email: "", password: "" }); const [showPassword, setShowPassword] = useState(false);
  const [rememberDevice, setRememberDevice] = useState(false);
  const [mode, setMode] = useState<"login" | "forgot" | "otp" | "reset">("login"); const [challenge, setChallenge] = useState<Challenge | null>(null); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  const finishLogin = (token: string, trustedDeviceToken?: string) => { localStorage.setItem("token", token); if (trustedDeviceToken) localStorage.setItem("trustedDeviceToken", trustedDeviceToken); const user = jwtDecode<DecodedToken>(token); toast.success("Sesión iniciada correctamente"); navigate(["Administrador", "Trabajador"].includes(user.Rol) ? "/pos/dashboard" : "/", { replace: true }); };
  const submitLogin = async () => { setBusy(true); try { const data = await loginUser({ email: form.email.trim(), password: form.password, trustedDeviceToken: localStorage.getItem("trustedDeviceToken") }); if (data.token) return finishLogin(data.token); setChallenge(data); setMode("otp"); toast.info(data.message); } catch (error) { toast.error(error instanceof Error ? error.message : "No pudimos iniciar sesión"); } finally { setBusy(false); } };
  const verify = async (code: string) => { if (!challenge) return; setBusy(true); try { const data = await verifyAuthCode({ challengeId: challenge.challengeId, code, purpose: challenge.purpose as "LOGIN" | "REGISTER", rememberDevice: challenge.purpose === "LOGIN" && rememberDevice }); if (data.token) finishLogin(data.token, data.trustedDeviceToken); else { toast.success(data.message); setMode("login"); } } catch (error) { toast.error(error instanceof Error ? error.message : "Código inválido"); } finally { setBusy(false); } };
  if (mode === "otp" && challenge) return <OtpPanel challenge={challenge} title={challenge.purpose === "REGISTER" ? "Confirma tu correo" : "Verifica tu acceso"} text="Escribe el código que enviamos a" busy={busy} onBack={() => setMode("login")} onSubmit={verify}/>;
  if (mode === "reset" && challenge) return <OtpPanel challenge={challenge} title="Crea una contraseña nueva" text="Enviamos un código de recuperación a" onBack={() => setMode("login")}>{(code, setCode) => <form noValidate className="mt-7 grid gap-6" onSubmit={async(e) => { e.preventDefault(); if (form.password.length < 10) return toast.error("Usa al menos 10 caracteres"); setBusy(true); try { const data = await resetPassword({ challengeId: challenge.challengeId, code, password: form.password }); toast.success(data.message); setMode("login"); } catch(error) { toast.error(error instanceof Error ? error.message : "No pudimos cambiarla"); } finally { setBusy(false); } }}><label className="block"><span className="auth-label">Código</span><input className="auth-input text-center text-xl tracking-[.3em]" required maxLength={6} inputMode="numeric" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g,""))}/></label><label className="block"><span className="auth-label">Contraseña nueva</span><input className="auth-input" minLength={10} required type="password" value={form.password} onChange={(e) => setForm({...form,password:e.target.value})}/></label><button disabled={busy || code.length !== 6} className="mt-2 min-h-12 w-full rounded-xl bg-primary font-bold text-white disabled:opacity-50">{busy ? "Guardando…" : "Cambiar contraseña"}</button></form>}</OtpPanel>;
  if (mode === "forgot") return <div className="rounded-3xl border border-black/5 bg-white p-6 shadow-xl sm:p-8"><button onClick={() => setMode("login")} className="text-sm font-bold text-primary">← Volver</button><h1 className="mt-5 text-3xl font-extrabold">Recuperar contraseña</h1><p className="mt-2 text-sm text-on-surface-variant">Te enviaremos un código temporal por correo.</p><form className="mt-7 grid gap-5" onSubmit={async(e) => { e.preventDefault(); setBusy(true); try { const data = await forgotPassword(form.email.trim()); setChallenge(data); setMode("reset"); toast.info(data.message); } catch(error) { toast.error(error instanceof Error ? error.message : "No pudimos continuar"); } finally { setBusy(false); } }}><label className="block"><span className="auth-label">Correo electrónico</span><input className="auth-input" required type="email" value={form.email} onChange={(e) => setForm({...form,email:e.target.value})}/></label><button disabled={busy} className="min-h-12 w-full rounded-xl bg-primary font-bold text-white disabled:opacity-50">{busy ? "Enviando…" : "Enviar código"}</button></form></div>;
  return <div className="rounded-3xl border border-black/5 bg-white p-6 shadow-xl shadow-primary/5 sm:p-8"><p className="text-sm font-bold uppercase tracking-widest text-secondary">Bienvenido</p><h1 className="mt-2 text-3xl font-extrabold">Iniciar sesión</h1><p className="mt-2 text-sm text-on-surface-variant">Después de validar tu contraseña enviaremos un PIN a tu correo.</p><form className="mt-7 space-y-5" onSubmit={(e) => { e.preventDefault(); submitLogin(); }}><label className="block"><span className="auth-label">Correo electrónico</span><div className="relative"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-outline" size={19}/><input className="auth-input pl-12" type="email" required autoComplete="email" placeholder="nombre@correo.com" value={form.email} onChange={(e) => setForm({...form,email:e.target.value})}/></div></label><label className="block"><span className="auth-label">Contraseña</span><div className="relative"><LockKeyhole className="absolute left-4 top-1/2 -translate-y-1/2 text-outline" size={19}/><input className="auth-input px-12" required autoComplete="current-password" placeholder="Ingresa tu contraseña" type={showPassword?"text":"password"} value={form.password} onChange={(e) => setForm({...form,password:e.target.value})}/><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-1/2 -translate-y-1/2 p-2 text-outline">{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></div><button type="button" onClick={() => setMode("forgot")} className="mt-2 text-sm font-bold text-primary hover:underline">Olvidé mi contraseña</button></label><label className="flex cursor-pointer items-start gap-3 rounded-xl bg-slate-50 px-3 py-3 text-sm"><input type="checkbox" checked={rememberDevice} onChange={(event) => setRememberDevice(event.target.checked)} className="mt-0.5 h-4 w-4 accent-primary"/><span><strong className="block text-on-surface">Confiar en este dispositivo</strong><span className="text-xs text-on-surface-variant">No solicitaremos el PIN durante 30 días. No lo uses en equipos compartidos.</span></span></label><button disabled={busy} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary font-bold text-white disabled:opacity-50">{busy&&<LoaderCircle className="animate-spin" size={20}/>}Continuar</button></form><p className="mt-6 text-center text-sm text-on-surface-variant">¿Necesitas una cuenta? <button onClick={() => onRegister?.(true)} className="font-bold text-primary hover:underline">Crear cuenta</button></p></div>;
}
