import { useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CalendarClock, PackageX, RefreshCw, Save, ShoppingCart, Trash2 } from "lucide-react";
import { useState } from "react";
import type { FormEvent } from "react";
import { toast } from "react-toastify";
import { deactivateInventoryLot, getInventoryAlerts, saveInventoryLot, updateMinimumStock } from "../../api/inventoryAlertsApi";

type StockRow = { stockId: number; product: string; presentation: string; code?: string; amount: number; minimumStock: number };
type StockAlert = StockRow & { type: "OUT_OF_STOCK" | "LOW_STOCK"; suggestedPurchase: number };
type LotAlert = { lotId: number; stockId: number; type: "EXPIRED" | "EXPIRING"; product: string; presentation: string; lotNumber: string; quantity: number; expirationDate: string };
type AlertData = { days: number; summary: { total: number; outOfStock: number; lowStock: number; expiring: number; expired: number }; stocks: StockRow[]; stockAlerts: StockAlert[]; lotAlerts: LotAlert[] };

export default function InventoryAlertsPage() {
  const client = useQueryClient(); const [days, setDays] = useState(30); const [editing, setEditing] = useState<number | null>(null); const [minimum, setMinimum] = useState(0);
  const [lot, setLot] = useState({ ID_Stock: 0, LotNumber: "", Quantity: 1, ExpirationDate: "" });
  const { data, isLoading, isFetching, error } = useQuery<AlertData>({ queryKey: ["inventory-alerts", days], queryFn: () => getInventoryAlerts(days) });
  const refresh = () => client.invalidateQueries({ queryKey: ["inventory-alerts"] });
  const saveMinimum = async (stockId: number) => { try { await updateMinimumStock(stockId, minimum); toast.success("Stock mínimo actualizado"); setEditing(null); refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "No se pudo guardar"); } };
  const submitLot = async (event: FormEvent) => { event.preventDefault(); try { await saveInventoryLot(lot); toast.success("Lote registrado para seguimiento"); setLot({ ID_Stock: 0, LotNumber: "", Quantity: 1, ExpirationDate: "" }); refresh(); } catch (e) { toast.error(e instanceof Error ? e.message : "No se pudo registrar el lote"); } };
  const cards = [{ label: "Sin existencia", value: data?.summary.outOfStock || 0, icon: PackageX, color: "text-red-700 bg-red-50" }, { label: "Stock bajo", value: data?.summary.lowStock || 0, icon: ShoppingCart, color: "text-amber-700 bg-amber-50" }, { label: "Por caducar", value: data?.summary.expiring || 0, icon: CalendarClock, color: "text-orange-700 bg-orange-50" }, { label: "Caducados", value: data?.summary.expired || 0, icon: AlertTriangle, color: "text-rose-700 bg-rose-50" }];
  return <section className="space-y-5">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-semibold text-[#c70063]">Inventario</p><h1 className="text-2xl font-extrabold text-slate-950">Alertas y reabastecimiento</h1><p className="text-sm text-slate-500">Controla mínimos, faltantes y lotes próximos a caducar.</p></div><button onClick={refresh} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 font-semibold text-slate-700 active:scale-[.98]"><RefreshCw size={17} className={isFetching ? "animate-spin" : ""}/>Actualizar</button></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(({ label, value, icon: Icon, color }) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-4"><div className={`mb-3 inline-flex rounded-xl p-2 ${color}`}><Icon size={20}/></div><p className="text-2xl font-extrabold">{value}</p><p className="text-sm text-slate-500">{label}</p></article>)}</div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error instanceof Error ? error.message : "No se pudieron cargar las alertas"}</div>}
    <article className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Existencias que requieren atención</h2><p className="text-sm text-slate-500">La sugerencia busca recuperar hasta el doble del mínimo.</p></div></div>
      {isLoading ? <p className="py-8 text-center text-slate-500">Cargando inventario…</p> : !data?.stockAlerts.length ? <p className="rounded-xl bg-emerald-50 p-4 text-emerald-800">No hay faltantes ni existencias por debajo del mínimo.</p> : <div className="grid gap-3">{data.stockAlerts.map((item) => <div key={item.stockId} className="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div><p className="font-bold text-slate-900">{item.product} · {item.presentation}</p><p className="text-sm text-slate-500">Existencia: {item.amount} · Mínimo: {item.minimumStock}</p></div><span className={`w-fit rounded-full px-3 py-1 text-xs font-bold ${item.type === "OUT_OF_STOCK" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-800"}`}>{item.type === "OUT_OF_STOCK" ? "Agotado" : "Stock bajo"}</span><p className="text-sm"><span className="text-slate-500">Compra sugerida</span> <strong>{item.suggestedPurchase}</strong></p></div>)}</div>}
    </article>
    <div className="grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><h2 className="text-lg font-bold">Configurar stock mínimo</h2><p className="mb-4 text-sm text-slate-500">Define el punto en que el sistema debe avisar por presentación.</p><div className="max-h-[430px] space-y-2 overflow-y-auto pr-1">{data?.stocks.map((stock) => <div key={stock.stockId} className="flex flex-col gap-2 rounded-xl bg-slate-50 p-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate font-semibold">{stock.product} · {stock.presentation}</p><p className="text-xs text-slate-500">Actual: {stock.amount}</p></div>{editing === stock.stockId ? <div className="flex gap-2"><input aria-label="Stock mínimo" type="number" min="0" value={minimum} onChange={(e) => setMinimum(Math.max(0, Number(e.target.value)))} className="w-24 rounded-xl border border-slate-300 px-3 py-2"/><button onClick={() => saveMinimum(stock.stockId)} className="rounded-xl bg-[#008b95] p-2.5 text-white"><Save size={18}/></button></div> : <button onClick={() => { setEditing(stock.stockId); setMinimum(stock.minimumStock); }} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm font-semibold">Mínimo: {stock.minimumStock}</button>}</div>)}</div></article>
      <article className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5"><h2 className="text-lg font-bold">Registrar lote y caducidad</h2><p className="mb-4 text-sm text-slate-500">El lote sólo clasifica la existencia; no incrementa el stock.</p><form onSubmit={submitLot} className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold sm:col-span-2">Producto / presentación<select required value={lot.ID_Stock || ""} onChange={(e) => setLot({ ...lot, ID_Stock: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"><option value="">Seleccionar</option>{data?.stocks.map((stock) => <option key={stock.stockId} value={stock.stockId}>{stock.product} · {stock.presentation}</option>)}</select></label><label className="text-sm font-semibold">Número de lote<input required value={lot.LotNumber} onChange={(e) => setLot({ ...lot, LotNumber: e.target.value })} placeholder="Ej. L2408A" className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-sm font-semibold">Cantidad del lote<input required type="number" min="1" value={lot.Quantity} onChange={(e) => setLot({ ...lot, Quantity: Number(e.target.value) })} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><label className="text-sm font-semibold sm:col-span-2">Fecha de caducidad<input required type="date" value={lot.ExpirationDate} onChange={(e) => setLot({ ...lot, ExpirationDate: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"/></label><button className="rounded-xl bg-[#c70063] px-4 py-3 font-bold text-white active:scale-[.98] sm:col-span-2">Guardar lote</button></form>
        <div className="mt-5 border-t border-slate-200 pt-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-bold">Caducidades detectadas</h3><label className="text-xs text-slate-500">Avisar en <select value={days} onChange={(e) => setDays(Number(e.target.value))} className="ml-1 rounded-lg border border-slate-300 bg-white px-2 py-1"><option value="15">15 días</option><option value="30">30 días</option><option value="60">60 días</option><option value="90">90 días</option></select></label></div>{!data?.lotAlerts.length ? <p className="text-sm text-slate-500">No hay lotes por caducar en este periodo.</p> : <div className="space-y-2">{data.lotAlerts.map((item) => <div key={item.lotId} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><div className="min-w-0 flex-1"><p className="truncate font-semibold">{item.product} · {item.presentation}</p><p className="text-xs text-slate-500">Lote {item.lotNumber} · {item.quantity} pzas. · {item.expirationDate}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.type === "EXPIRED" ? "bg-red-100 text-red-700" : "bg-orange-100 text-orange-700"}`}>{item.type === "EXPIRED" ? "Caducado" : "Próximo"}</span><button aria-label="Retirar lote de alertas" onClick={async () => { await deactivateInventoryLot(item.lotId); refresh(); }} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div>)}</div>}</div>
      </article></div>
  </section>;
}
